[package]
name = "spring-rs-test"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
spring = "0.4.0"
spring-rs = "0.1.0"
spring-web = "0.4.3"
tokio = { version = "1.45.1", features = ["full"] }
