[package]
name = "third_trial"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonpath = "0.1.1"
reqwest = "0.12.15"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["full"] }
